external_host_name = "moneyclaims-legal.perftest.platform.hmcts.net"
idam_api_url = "https://idam-api.perftest.platform.hmcts.net"
authentication_web_url = "https://idam-web-public.perftest.platform.hmcts.net"
fees_api_url = "http://fees-register-api-perftest.service.core-compute-perftest.internal"
payments_api_url = "http://payment-api-perftest.service.core-compute-perftest.internal"
feature_certificateOfService = "false"
feature_inversionOfControl = "true"
capacity = "2"
